### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by aaminjsr** [bashar94/STOCK-MANAGER-ADVANCE-MODIFIED#3]
bhai assalamualaikum
amar aktu MODIFIED kora lagbe
customer kichu kinle due list tahkbe oi customer jodi abar kinte ashe tahole bill korle previous due + notun amount ak satha show korbe total due amount and pos also aita ki kore korbo apni jodi help korten? please ? ami pay korbo somossha nai..

thank you advance bhai

**Comment by bashar94** [comment]
WalaikumAssalam,

Brother this is to open an issue of this project when someone faces any problem. I hope you understand, if you are a developer then go through the source code of the project, you will understand.

Good luck!
