### ISSUE TITLE
DATABASE? 

### ISSUE THREAD

**Issue by hamzaisa2019** [bashar94/STOCK-MANAGER-ADVANCE-MODIFIED#4]
I didn't find the database in stock manager advance software folder, please any one help me to explain More

**Comment by bashar94** [comment]
@hamzaisa2019 It was one or my early projects. As per as I can remember they call an API to get all SQL queries when you install the project and execute them to create database. I concatenated some extra fields to store new data.

**Comment by hamzaisa2019** [comment]
Sir 
What is the API explain please

**Comment by bashar94** [comment]
I didn't get your question, did you ask me what API means? or do you want to know where is the API thing?

**Comment by hamzaisa2019** [comment]
Yes I want to know where is the API things

**Comment by hamzaisa2019** [comment]
Yes sir 
 I want to know where is the API things please

**Comment by bashar94** [comment]
I just went through some codes and I can't remember exactly where they did this, if I can find it I will let you know. Also I found these things : [/tree/master/files](https://github.com/bashar94/STOCK-MANAGER-ADVANCE-MODIFIED/tree/master/files) and there are sql files

**Comment by hamzaisa2019** [comment]
Ok ok am waiting sir , till you find it 
Let me go for the tree/master/files first, if something wrong I will contact you again sir 
Thanks 🙏🙏🙏

**Comment by bashar94** [comment]
Meanwhile you can go through to codes

**Comment by hamzaisa2019** [comment]
sir how can i pay for the code

**Comment by bashar94** [comment]
@hamzaisa2019 here is the official link to the product https://tecdiary.net/products/stock-manager-advance-with-all-modules
